import { readFileSync, writeFileSync, readdirSync, lstatSync, readlinkSync, symlinkSync, unlinkSync, mkdirSync } from "node:fs";
import { resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { Schema } from "effect";
import { Config } from "@opencode/schema";
import { parse, type ParseError } from "jsonc-parser";

export const root = fileURLToPath(new URL("../", import.meta.url));
export const profiles = ["personal", "work"] as const;
type NativeConfig = Schema.Codec.Encoded<typeof Config.Info>;
type Agent = NonNullable<NativeConfig["agents"]>[string];
type Command = NonNullable<NativeConfig["commands"]>[string];
type Settings = Omit<NativeConfig, "agents" | "commands" | "skills" | "$schema">;
type Shared = { settings: Settings; agents: Record<string, Agent> };
type Profile = {
  settings: Settings;
  agents: Record<string, Partial<Agent>>;
  builtin_agents: Record<string, Agent>;
  commands: Record<string, Command>;
  skills: string[];
};

export function readSource<T>(name: string): T {
  const errors: ParseError[] = [];
  const result = parse(readFileSync(resolve(root, "config", `${name}.jsonc`), "utf8"), errors, { allowTrailingComma: true });
  if (errors.length) throw new Error(`${name}: invalid JSONC: ${JSON.stringify(errors)}`);
  return result as T;
}

function markdown(reference: string | undefined, kind: "agents" | "commands"): string {
  const match = reference?.match(/^\{file:([^}]+)\}$/);
  if (!match || !match[1].startsWith(`${kind}/`) || match[1].includes("archive/")) {
    throw new Error(`Expected an active ${kind}/ Markdown reference, got ${reference}`);
  }
  const path = resolve(root, match[1]);
  if (!path.startsWith(resolve(root, kind) + "/")) throw new Error(`Invalid source path: ${reference}`);
  return readFileSync(path, "utf8");
}

export function composeProfile(name: typeof profiles[number]): { config: NativeConfig; skills: string[] } {
  const shared = readSource<Shared>("shared");
  const profile = readSource<Profile>(name);
  const agents: Record<string, Agent> = { ...profile.builtin_agents };
  for (const [id, overrides] of Object.entries(profile.agents)) {
    if (!shared.agents[id]) throw new Error(`${name}: unknown shared agent ${id}`);
    // Replace permission arrays as a whole: their order controls precedence.
    const agent = { ...shared.agents[id], ...overrides };
    agents[id] = { ...agent, system: markdown(agent.system, "agents") };
  }
  const commands = Object.fromEntries(Object.entries(profile.commands).map(([id, command]) => {
    if (!command.agent || !profile.agents[command.agent]) throw new Error(`${name}: ${id} has an unselected agent`);
    return [id, { ...command, template: markdown(command.template, "commands") }];
  }));
  const config = {
    $schema: "./opencode.schema.json",
    ...shared.settings,
    ...profile.settings,
    plugins: [...shared.settings.plugins ?? [], ...profile.settings.plugins ?? []],
    agents,
    commands,
  };
  Schema.decodeUnknownSync(Config.Info)(config);
  if (!config.default_agent || !profile.agents[config.default_agent] || agents[config.default_agent].mode === "subagent") {
    throw new Error(`${name}: default_agent must select an active primary agent`);
  }
  for (const skill of profile.skills) {
    if (!/^[a-z0-9-]+$/.test(skill)) throw new Error(`Invalid skill: ${skill}`);
    readFileSync(resolve(root, "skills", skill, "SKILL.md"));
  }
  return { config, skills: profile.skills };
}

export function renderProfile(name: typeof profiles[number]): string {
  return `// Generated by pnpm config:generate. Edit config/*.jsonc, agents/, or commands/.\n${JSON.stringify(composeProfile(name).config, null, 2)}\n`;
}

function syncSkills(name: typeof profiles[number], skills: string[], check: boolean) {
  const directory = resolve(root, name, "skills");
  // Replace the old whole-library link without touching the library itself.
  if (lstatSync(directory, { throwIfNoEntry: false })?.isSymbolicLink()) {
    if (check) throw new Error(`${name}: replace the whole-library skills link with config:generate`);
    unlinkSync(directory);
  }
  if (!check) mkdirSync(directory, { recursive: true });
  const selected = new Set(skills);
  for (const existing of readdirSync(directory)) {
    if (selected.has(existing)) continue;
    const path = resolve(directory, existing);
    if (check || !lstatSync(path).isSymbolicLink()) throw new Error(`${name}: unexpected skill entry ${existing}`);
    unlinkSync(path);
  }
  for (const skill of skills) {
    const path = resolve(directory, skill);
    const target = relative(directory, resolve(root, "skills", skill));
    const stat = lstatSync(path, { throwIfNoEntry: false });
    if (stat?.isSymbolicLink() && readlinkSync(path) === target) continue;
    if (check || stat) throw new Error(`${name}: missing or unexpected link for ${skill}`);
    symlinkSync(target, path, "dir");
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  // Validate both profiles before writing either one.
  const generated = profiles.map(name => ({ name, text: renderProfile(name), skills: composeProfile(name).skills }));
  for (const { name, text, skills } of generated) {
    const path = resolve(root, name, "opencode.jsonc");
    if (check) {
      if (readFileSync(path, "utf8") !== text) throw new Error(`${name}: generated config is stale; run pnpm config:generate`);
    } else {
      writeFileSync(path, text);
    }
    syncSkills(name, skills, check);
    console.log(`${name}: ${check ? "up to date" : "generated"}`);
  }
}
