format = """
$username$hostname$directory$git_branch$git_status$fill$nodejs$rust$python$aws
$character
"""
add_newline = false
palette = "clean"

[palettes.clean]
fg = "#cdcdcd"
muted = "#606079"
blue = "#6e94b2"
green = "#99b782"
yellow = "#e8b589"
red = "#c48282"
lavender = "#c9b1ca"

[fill]
symbol = " "

[username]
show_always = true
format = "[$user]($style) "
style_user = "bold yellow"

[hostname]
ssh_only = false
disabled = false
detect_env_vars = ["!TMUX", "SSH_CONNECTION"]
format = "@[$hostname]($style) "
style = "bold blue"

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold #cdd6f4"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Debian = ""
Fedora = ""
Linux = ""
Macos = " "
Ubuntu = ""
Windows = ""

[directory]
style = "bold fg"
truncate_to_repo = false
truncation_length = 999
format = "[$path]($style)"
home_symbol = "~"

[git_branch]
symbol = ""
style = "bold green"
format = " [$branch]($style)"

[git_status]
style = "bold yellow"
format = " ([$all_status$ahead_behind]($style) )"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[nodejs]
symbol = ""
style = "bold green"
format = "[node:$version]($style) "

[rust]
symbol = ""
style = "#f38ba8"
format = "[rust:$version]($style) "

[python]
symbol = ""
style = "#f9e2af"
format = "[py:$version]($style) "

[aws]
symbol = ""
style = "#ff964f"
format = "[aws:$profile]($style)"
force_display = false
disabled = false

[shell]
disabled = false
format = "[$indicator]($style)"
style = "muted"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
