-- Telescope Preview with word wrap
-- vim.api.nvim_create_autocmd("User", {
-- 	pattern = "TelescopePreviewerLoaded",
-- 	callback = function(args)
-- 		if args.data.filetype ~= "help" then
-- 			vim.wo.number = true
-- 			if args.data.bufname:match("%.csv$") then
-- 				vim.wo.wrap = false
-- 			else
-- 				vim.wo.wrap = true
-- 			end
-- 		end
-- 	end,
-- })
