-- local M = {}
--
-- M.default_theme = "catppuccin"
-- M.state_file = vim.fn.stdpath("state") .. "/colorscheme.txt"
--
-- local function configure_theme(theme_name)
-- 	if theme_name == "catppuccin" then
-- 		require("catppuccin").setup({
-- 			flavour = "mocha",
-- 			transparent_background = true,
-- 			integrations = {
-- 				notify = true,
-- 			},
-- 			custom_highlights = function(colors)
-- 				return {
-- 					FloatBorder = { fg = colors.blue },
-- 				}
-- 			end,
-- 		})
-- 	end
-- end
--
-- local function read_theme_state()
-- 	if vim.fn.filereadable(M.state_file) == 0 then
-- 		return nil
-- 	end
--
-- 	local lines = vim.fn.readfile(M.state_file)
-- 	local theme_name = lines[1]
-- 	if theme_name == nil or theme_name == "" then
-- 		return nil
-- 	end
-- 	return theme_name
-- end
--
-- local function write_theme_state(theme_name)
-- 	local ok = vim.fn.writefile({ theme_name }, M.state_file)
-- 	if ok ~= 0 then
-- 		vim.notify("Failed to persist colorscheme: " .. theme_name, vim.log.levels.ERROR)
-- 	end
-- end
--
-- function M.apply(theme_name)
-- 	local available_themes = vim.fn.getcompletion("", "color")
-- 	if not vim.tbl_contains(available_themes, theme_name) then
-- 		vim.notify("Unknown colorscheme: " .. theme_name, vim.log.levels.ERROR)
-- 		return nil
-- 	end
--
-- 	configure_theme(theme_name)
-- 	vim.cmd.colorscheme(theme_name)
-- 	write_theme_state(theme_name)
-- 	return theme_name
-- end
--
-- function M.apply_saved_or_default()
-- 	local theme_name = read_theme_state() or M.default_theme
-- 	local applied_theme = M.apply(theme_name)
-- 	if applied_theme ~= nil then
-- 		return applied_theme
-- 	end
-- 	return M.apply(M.default_theme)
-- end
--
-- return M
